// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7rpROa1TXubAYeijgEKtZ6zYTYzVog9I',
    appId: '1:952237951855:android:119a1bfc67a6462737f69a',
    messagingSenderId: '952237951855',
    projectId: 'fitness-tracker-f2248',
    storageBucket: 'fitness-tracker-f2248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDes3a583wZtDIrdLRz8ORu6gAC95B6Ps0',
    appId: '1:952237951855:ios:73320a2fe6349dfa37f69a',
    messagingSenderId: '952237951855',
    projectId: 'fitness-tracker-f2248',
    storageBucket: 'fitness-tracker-f2248.firebasestorage.app',
    iosBundleId: 'com.example.fitQuestProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi8xTn7FdgAeAHsGx1iQfhR9UuI66c8AI',
    appId: '1:952237951855:web:4468638c9f33b52c37f69a',
    messagingSenderId: '952237951855',
    projectId: 'fitness-tracker-f2248',
    authDomain: 'fitness-tracker-f2248.firebaseapp.com',
    storageBucket: 'fitness-tracker-f2248.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDes3a583wZtDIrdLRz8ORu6gAC95B6Ps0',
    appId: '1:952237951855:ios:73320a2fe6349dfa37f69a',
    messagingSenderId: '952237951855',
    projectId: 'fitness-tracker-f2248',
    storageBucket: 'fitness-tracker-f2248.firebasestorage.app',
    iosBundleId: 'com.example.fitQuestProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi8xTn7FdgAeAHsGx1iQfhR9UuI66c8AI',
    appId: '1:952237951855:web:e1943036a02001e937f69a',
    messagingSenderId: '952237951855',
    projectId: 'fitness-tracker-f2248',
    authDomain: 'fitness-tracker-f2248.firebaseapp.com',
    storageBucket: 'fitness-tracker-f2248.firebasestorage.app',
  );

}